### PR TITLE
Apply linter checks and fix issues

### PR DESCRIPTION
**Pull request by dersim-davaod**
Checks:

* [ ] Update changelog
* [x] Rebase to `dev` branch
* [x] Assign reviewers

Linked issues: mapbox/vision-ios-examples#85
Resolves: #126

### CODE REVIEW

**Comment by IodaMikeMapbox** [comment]
Please rebase the branch

**Comment by chezzdev** [comment]
I think this PR can be a good place to specify folder when we're calling `swiftlint` in a build phase.
Right now each target runs `swiftlint` on the whole project and we may have multiple identical warnings for the same line. If each target specified its folder then we wouldn't see such behavior. 

The second improvement we may do here is to add `Examples/Carthage` as an exclusion to `.swiftformat` and `.swiftlint.yml`.

What do you think?

**Comment by dersim-davaod** [comment]
> I think this PR can be a good place to specify folder when we're calling swiftlint in a build phase.
Right now each target runs swiftlint on the whole project and we may have multiple identical warnings for the same line. If each target specified its folder then we wouldn't see such behavior.

Totally agree!

> The second improvement we may do here is to add Examples/Carthage as an exclusion to .swiftformat and .swiftlint.yml.

Agree, especially `swiftlint`'s config already contains it.

**Comment by dersim-davaod** [comment]
@chezzdev / @IodaMikeMapbox  could you please try to enable listing with a specific paths for each target? Look like it doesn't work as expected.

**Comment by chezzdev** [comment]
`swiftlint lint --config ${PROJECT_DIR}/.swiftlint.yml --path MapboxVisionAR` works for me.

**Comment by dersim-davaod** [comment]
Eventually the reason was in `excluded` section of `.swiftlint.yml` config file.
The parser ignored the exclude-declaration for `Reachability.swift` file so I've disable linting in `Reachability.swift` file itself.

**Pull request merged**
